pull_request_template:
  - name: "Development Template"
    description: "Use this template for development branches."
    template: "PULL_REQUEST_TEMPLATE_DEV.md"
    branches:
      - "cm*-*dev"

  - name: "SIT Template"
    description: "Use this template for SIT branches."
    template: "PULL_REQUEST_TEMPLATE_SIT.md"
    branches:
      - "cm*-*SIT"
