name: Update Pull Request on Merge
on:
  pull_request:
    types: [closed]
permissions:
  pull-requests: write  # Allows the workflow to write to pull requests
jobs:
  update_on_merge:
    if: github.event.pull_request.merged == true  # Only run if the pull request was merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge main into the current branch
        run: |
          # Fetch the latest changes from the remote repository
          git fetch origin
          # Merge the main branch into the current branch
          git merge origin/main

      - name: Update Pull Request on Merge
        run: |
          # Extract details from the pull request
          PR_NUMBER=${{ github.event.pull_request.number }}
          USER_DESCRIPTION="${{ github.event.pull_request.body }}"
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}

          # Prepare the extended description
          EXTENDED_DESCRIPTION="Merged main into branch: $BRANCH_NAME\n\nUser Description:\n$USER_DESCRIPTION"

          echo "Extended Description: $EXTENDED_DESCRIPTION"

          # Update the pull request body using GitHub API
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            -d "{\"body\": \"$EXTENDED_DESCRIPTION\"}"
