name: Update Pull Request on Merge

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write  # Allows the workflow to write to pull requests

jobs:
  update_on_merge:
    if: github.event.pull_request.merged == true  # Only run if the pull request was merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Pull Request on Merge
        run: |
          # Extract details from the pull request
          PR_NUMBER=${{ github.event.pull_request.number }}
          USER_DESCRIPTION="${{ github.event.pull_request.body }}"
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          
          # Extract ticket number from the branch name
          TICKET_NUMBER=$(echo "$BRANCH_NAME" | cut -d'-' -f1)

          # Escape newlines and quotes in USER_DESCRIPTION
          USER_DESCRIPTION_ESCAPED=$(echo "$USER_DESCRIPTION" | sed ':a;N;$!ba;s/\n/\\n/g;s/"/\\"/g')

          # Prepare the extended description
          EXTENDED_DESCRIPTION="Ticket Number: $TICKET_NUMBER\nChange:\n$USER_DESCRIPTION_ESCAPED"

          echo "Extended Description: $EXTENDED_DESCRIPTION"

          # Update the pull request body using GitHub API
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.Nitesh_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            -d "{\"body\": \"$EXTENDED_DESCRIPTION\"}"
