name: Pull Request Management

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  manage_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Pull Request Details
        id: pr_details
        run: |
          echo "Owner: ${{ github.actor }}"
          echo "Branch Name: ${{ github.head_ref }}"
          
          # Extract ticket number and short description from the branch name
          BRANCH_NAME="${{ github.head_ref }}"
          TICKET_NUMBER=$(echo "$BRANCH_NAME" | cut -d'-' -f1)
          SHORT_DESCRIPTION=$(echo "$BRANCH_NAME" | cut -d'-' -f2)
          ENVIRONMENT=$(echo "$BRANCH_NAME" | cut -d'-' -f3)

          echo "Short Description: $SHORT_DESCRIPTION"
          echo "Ticket Number: $TICKET_NUMBER"
          echo "Environment: $ENVIRONMENT"

          # Output the details for later use
          echo "::set-output name=short_description::$SHORT_DESCRIPTION"
          echo "::set-output name=ticket_number::$TICKET_NUMBER"
          echo "::set-output name=environment::$ENVIRONMENT"

      - name: Output Pull Request Details
        run: |
          echo "Pull Request Owner: ${{ github.actor }}"
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Short Description: ${{ steps.pr_details.outputs.short_description }}"
          echo "Ticket Number: ${{ steps.pr_details.outputs.ticket_number }}"
          echo "Environment: ${{ steps.pr_details.outputs.environment }}"
          echo "Reviewers: ${{ toJson(github.event.pull_request.requested_reviewers) }}"
          echo "Comments: ${{ github.event.pull_request.body }}"
