name: Update Pull Request Description

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write  # Allows the workflow to write to pull requests
  issues: read          # Allows the workflow to read issues (for comments)

jobs:
  update_description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Pull Request Description
        run: |
          # Extract details from the pull request
          OWNER="niteshbhat"
          TITLE="Update README.md"
          USER_DESCRIPTION="hellow"
          BRANCH_NAME="cnd112-discrption-dev"
          
          # Extract ticket number and short description from the branch name
          TICKET_NUMBER=$(echo "$BRANCH_NAME" | cut -d'-' -f1)
          SHORT_DESCRIPTION=$(echo "$BRANCH_NAME" | cut -d'-' -f2)
          ENVIRONMENT=$(echo "$BRANCH_NAME" | cut -d'-' -f3)
          
          # Escape newlines in USER_DESCRIPTION
          USER_DESCRIPTION_ESCAPED=$(echo "$USER_DESCRIPTION" | sed ':a;N;$!ba;s/\n/\\n/g')
          
          # Create the new pull request body with a GUI-like format
          PR_BODY=$(jq -n \
            --arg owner "$OWNER" \
            --arg title "$TITLE" \
            --arg user_desc "$USER_DESCRIPTION_ESCAPED" \
            --arg short_desc "$SHORT_DESCRIPTION" \
            --arg ticket_num "$TICKET_NUMBER" \
            --arg env "$ENVIRONMENT" \
            --arg comments "" \
            '{body: "## Pull Request Details\n\n**Pull Request Owner:** \($owner)\n\n**Pull Request Title:** \($title)\n\n**User Description:**\n\($user_desc)\n\n**Short Description:** \($short_desc)\n\n**Ticket Number:** \($ticket_num)\n\n**Environment:** \($env)\n\n**Comments:**\n\($comments)\n"}'
          )

          # Debugging: Print the PR_BODY to logs
          echo "PR_BODY: $PR_BODY"

          # Update the pull request body using GitHub API
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/niteshbhat/ReactForms/pulls/10 \
            -d "$PR_BODY"
